spring.application.name=MediCall
spring.datasource.url=jdbc:postgresql://localhost:5432/medicall
spring.datasource.username=postgres
spring.datasource.password=2316

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG